name: Ingest every 10 minutes

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Print APP_URL
        shell: bash
        run: |
          echo "APP_URL=${APP_URL}"
          echo "LEN=${#APP_URL}"
        env:
          APP_URL: ${{ secrets.APP_URL }}

      - name: Healthcheck (print body, never fail)
        shell: bash
        run: |
          code=$(curl -s -w "%{http_code}" -o /tmp/health "$APP_URL/api/health" || echo "000")
          echo "HEALTH HTTP=${code}"
          [ -f /tmp/health ] && cat /tmp/health || true
          exit 0
        env:
          APP_URL: ${{ secrets.APP_URL }}

      - name: Call ingest (dryRun=false, print body, never fail)
        shell: bash
        run: |
          code=$(curl -s -w "%{http_code}" -o /tmp/resp -X POST "$APP_URL/api/ingest" \
            -H "content-type: application/json" \
            -d '{"dryRun":false}' || echo "000")
          echo "INGEST HTTP=${code}"
          [ -f /tmp/resp ] && cat /tmp/resp || true
          if [ "$code" -lt 200 ] || [ "$code" -ge 400 ]; then
            echo "::warning::ingest returned ${code}";
          fi
        env:
          APP_URL: ${{ secrets.APP_URL }}