name: Ingest every 10 minutes

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Print APP_URL
        run: |
          echo "APP_URL=${APP_URL}"
          echo "LEN=${#APP_URL}"
        env:
          APP_URL: ${{ secrets.APP_URL }}

      - name: Healthcheck
        shell: bash
        run: |
          set -euo pipefail
          CODE=$(curl -sS -w "%{http_code}" -o /tmp/health "$APP_URL/api/health")
          echo "HTTP ${CODE}"
          cat /tmp/health
        env:
          APP_URL: ${{ secrets.APP_URL }}

      - name: Call ingest (dryRun=false)
        shell: bash
        run: |
          set -euo pipefail
          CODE=$(curl -sS -w "%{http_code}" -o /tmp/resp -X POST "$APP_URL/api/ingest" \
            -H "content-type: application/json" \
            -d '{"dryRun":false}')
          echo "HTTP ${CODE}"
          cat /tmp/resp
        env:
          APP_URL: ${{ secrets.APP_URL }}
