name: Ingest every 10 minutes

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Call /api/ingest
        run: |
          curl -s -X POST "$APP_URL/api/ingest" \
            -H "content-type: application/json" \
            -d '{"dryRun":false}'
        env:
          APP_URL: ${{ secrets.APP_URL }}