name: Ingest every 10 minutes

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-ingest:
    runs-on: ubuntu-latest
    steps:
      # APP_URL? secrets/vars/????? ?? ??
      - name: Resolve APP_URL
        shell: bash
        run: |
          if [ -n "${{ secrets.APP_URL }}" ]; then
            echo "APP_URL=${{ secrets.APP_URL }}" >> $GITHUB_ENV
          elif [ -n "${{ vars.APP_URL }}" ]; then
            echo "APP_URL=${{ vars.APP_URL }}" >> $GITHUB_ENV
          else
            echo "APP_URL=https://coin-calendar.vercel.app" >> $GITHUB_ENV
          fi
          echo "::notice::APP_URL=[$APP_URL]"

      - name: DNS & HEAD (IPv4)
        shell: bash
        run: |
          set -x
          host="$(echo "$APP_URL" | sed -E 's@https?://([^/]+).*@\1@')"
          getent hosts "$host" || true
          curl -4 -vI --connect-timeout 10 --max-time 20 "$APP_URL/api/health" || true

      - name: Health (print body)
        shell: bash
        run: |
          code=$(curl -4 -s -w "%{http_code}" -o /tmp/health "$APP_URL/api/health" || echo "000")
          echo "HEALTH HTTP=$code"
          [ -f /tmp/health ] && cat /tmp/health || true

      - name: Diag (print body)
        shell: bash
        run: |
          code=$(curl -4 -s -w "%{http_code}" -o /tmp/diag "$APP_URL/api/diag" || echo "000")
          echo "DIAG HTTP=$code"
          [ -f /tmp/diag ] && cat /tmp/diag || true

      - name: Ingest (dryRun=false)
        shell: bash
        run: |
          code=$(curl -4 -s -w "%{http_code}" -o /tmp/resp -X POST "$APP_URL/api/ingest" \
            -H "content-type: application/json" \
            -d '{"dryRun":false}' || echo "000")
          echo "INGEST HTTP=$code"
          [ -f /tmp/resp ] && cat /tmp/resp || true